### ISSUE TITLE
Sorting by size is incorrect when searching by string

### ISSUE THREAD

**Issue by patrickdevarney** [pschraut/UnityHeapExplorer#4]
Repro:
1. Open list of native objects
2. Search with a string that returns many results
3. Sort by size

Expected that the objects are correctly sorted by size.

Actual result is chunks of assets are sorted by size, then size appears to reset when a new group of assets is met.

**Comment by patrickdevarney** [comment]
Initial guess is that this is related to AbstractTreeView.SortItemsRecursive seeming to sort groups of assets rather than the full tree, but I have yet to find the confirmed culprit.

**Comment by patrickdevarney** [comment]
![Capture](https://user-images.githubusercontent.com/11896025/113626442-ce105580-9627-11eb-8f4a-1b4aa917e744.JPG)

**Comment by pschraut** [comment]
Thank you for the bug-report. I'm able to reproduce the issue. I think you're spot-on with "sort groups of assets rather than the full tree". I hopefully find time to look into the issue at the weekend, but it's more likely that it's a weekend after that.

**Comment by patrickdevarney** [comment]
Excellent! I gave it a shot myself but quickly ended up in an infinite recursive loop.

Also, thank you for creating and maintaining such an amazing tool! I use it nearly every week 👍

**Comment by jojo59516** [comment]
For now, when searching something, the profiler just simply filter out items that don't match the pattern. In other words, searching **cannot** break groups, while sorting is in groups.
Note that the result even contains groups, and the items are "correctly" indented.

So, it is a "feature" (may not be designed by the author) rather than a bug :)

**Comment by pschraut** [comment]
This should be fixed in 3.9.0, which went just online. The changes to get this working can be found [here](https://github.com/pschraut/UnityHeapExplorer/commit/43442d0690223a2c83e1e2380d94203a9ec52ddc).

I wasn't able to get sorting to work by using the [TreeView.searchString](https://docs.unity3d.com/ScriptReference/IMGUI.Controls.TreeView-searchString.html) API, so I implemented item filtering myself.

Filtering works by adding all items that pass the [TreeView.DoesItemMatchSearch](https://docs.unity3d.com/ScriptReference/IMGUI.Controls.TreeView.DoesItemMatchSearch.html) check to a single parent node, see [here](https://github.com/pschraut/UnityHeapExplorer/commit/43442d0690223a2c83e1e2380d94203a9ec52ddc#diff-b06240cb032af6c11516ad25eb94c3c3aa8fb30aee5aa42070d0e94059dbcca4R167). I also fixed that the items are no longer indented when a search is active, see [here](https://github.com/pschraut/UnityHeapExplorer/commit/43442d0690223a2c83e1e2380d94203a9ec52ddc#diff-b06240cb032af6c11516ad25eb94c3c3aa8fb30aee5aa42070d0e94059dbcca4R365).

Please let me know whether it works for you.

**Comment by patrickdevarney** [comment]
Just tested and it works perfectly! Thank you for the update
